### ISSUE TITLE
Plyer module is not found

### ISSUE THREAD

**Issue by prankapo** [Sumit3301/Pomodoro-Timer#1]
Running the script on my system generated the following traceback error:
` python3 pomodoro.py   

Traceback (most recent call last):
  File "pomodoro.py", line 6, in <module>
    import player
  File "/media/praneet/OS/DOS/PROGRAMS/Pomodoro-Timer-main/player.py", line 2, in <module>
    import plyer
ModuleNotFoundError: No module named 'plyer'`

**Comment by Sumit3301** [comment]
Install plyer using the command
pip install player then run
